# Generated by Django 4.0.1 on 2022-01-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='Article.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='note',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='prix',
            field=models.FloatField(),
        ),
    ]
