# Generated by Django 3.1.5 on 2022-02-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20220201_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
