# Generated by Django 4.0.1 on 2022-02-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0004_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prix', models.FloatField()),
                ('note', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
