# Generated by Django 4.0.1 on 2022-02-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='wtf', upload_to='chicks/'),
            preserve_default=False,
        ),
    ]
