# Generated by Django 4.0.1 on 2022-02-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(upload_to='Projet Django/monprojet/static/images/articles/'),
        ),
    ]
